template_files: {}
alertmanager_config: |
  global:
    resolve_timeout: 1m
    slack_api_url: 'https://hooks.slack.com/services/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'

  route:
    receiver: 'slack-notifications'
    repeat_interval: 1s

  receivers:
  - name: 'slack-notifications'
    slack_configs:
    - channel: '#promethuesalerting'
      send_resolved: true
      title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
      text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"  
