route:
    receiver: 'slack'

receivers:
    - name: 'slack'
      slack_configs:
          - send_resolved: true
            text: "{{ .CommonAnnotations.description }}"
            username: 'Prometheus'
            channel: '#promethuesalerting'
            api_url: 'https://hooks.slack.com/services/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'    

