global:
  resolve_timeout: 5m
  
route:
  receiver: 'slack-notifications'
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
receivers:
- name: 'slack-notifications'
  slack_configs:
  - api_url: https://hooks.slack.com/services/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
    channel: '#promethuesalerting'        
    send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname','dev','instance']  

