route:
  receiver: 'Mail Alert'
  # group_by: [ alertname ]
  repeat_interval: 30s
  group_wait: 15s
  group_interval: 15s

receivers:
  - name: 'Mail Alert'
    email_configs:
      - smarthost: 'smtp.gmail.com:587'
        auth_username: 'akkishiva@platformatory.com'
        auth_password: "Omganesh@066"
        from: 'akkishiva@platformatory.com'
        to: 'akkishivaprakash@gmail.com'
        headers:
          subject: 'Prometheus Mail Alerts'
