#!/bin/bash
podman exec ansible-control bash -c "cp /root/.ssh/id_rsa.pub /usr/share/cp-ansible-sandbox/id_rsa.pub"
podman exec zookeeper1 bash -c "cat /usr/share/cp-ansible-sandbox/id_rsa.pub >> /root/.ssh/authorized_keys"
podman exec zookeeper2 bash -c "cat /usr/share/cp-ansible-sandbox/id_rsa.pub >> /root/.ssh/authorized_keys"
podman exec zookeeper3 bash -c "cat /usr/share/cp-ansible-sandbox/id_rsa.pub >> /root/.ssh/authorized_keys"
podman exec kafka1 bash -c "cat /usr/share/cp-ansible-sandbox/id_rsa.pub >> /root/.ssh/authorized_keys"
podman exec kafka2 bash -c "cat /usr/share/cp-ansible-sandbox/id_rsa.pub >> /root/.ssh/authorized_keys"
podman exec kafka3 bash -c "cat /usr/share/cp-ansible-sandbox/id_rsa.pub >> /root/.ssh/authorized_keys"
podman exec control-center bash -c "cat /usr/share/cp-ansible-sandbox/id_rsa.pub >> /root/.ssh/authorized_keys"
podman exec zookeeper1 bash -c "service ssh start"
podman exec zookeeper2 bash -c "service ssh start"
podman exec zookeeper3 bash -c "service ssh start"
podman exec kafka1 bash -c "service ssh start"
podman exec kafka2 bash -c "service ssh start"
podman exec kafka3 bash -c "service ssh start"
podman exec control-center bash -c "service ssh start"
